language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - extra-android-m2repository
    - android-27

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

sudo: required

cache:
  directories:
    - $HOME/.gradle
